---
title: "Avoid_close_relationship_between_students_and_teachers"
author: "Wenlong"
date: "4/23/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

近日来，由于武汉和北大某些不可描述的事件，某些导师与学生之间复杂的关系暴露于公众的视线；尤其是有些不可描述的关系，甚至造成了受害者自杀身亡的悲剧，许多导师的职业道德被严重质疑。对于类似事件，笔者的观点向来是一致的：学生与老师之间，在师生关系的存续期间，**"师生恋"是需要禁止的**。

导师与学生之间的关系，是典型的权利不对等关系，有些情况下，导师对学生的工作内容，绩效评价乃至学成毕业有着“生杀大权”。在这种情况下，从保护权利“弱者”的角度出发，导师需要在强力监督下，洁身自好，有职业道德得从事相关工作。如果没有这些强制要求，当学生和导师产生超出正常范围的关系时，旁观者怎么判断学生是在自愿的，还是导师利用手中权力胁迫的呢？在某些情况下，对于某些学生来说，导师要求“喊爸爸”就得喊爸爸，导师饿了就得及时送饭，导师要求晚上来“暖床”就得准时出现，等等。很难想象，这些事情会是学生心甘情愿来完成的。


即使导师没有强制胁迫学生，有些时候，涉世未深的学生在见多识广的导师面前，跟一张白纸没有什么区别。例如一位三十到四十岁的相貌端正、温文儒雅、谈吐不凡的男性导师，极易吸引一些女学生的注意甚至倾慕。但是，这种崇拜等同于爱慕吗？当女学生也到了三四十岁，她还会认为自己的决定是正确的吗？即使是需要被“第三者”也是值得的吗？往往这种情况下，师生恋对学生都是不公平的。当她/他发现不公平，想要抗争的时候，前文在提到的权利不对等就又一次发挥了作用。北大某女学生的自杀事件，据调查就与其导师有着密不可分的关系。

说到这里，可能有些处于权利“优势”的朋友们也一肚子怨言：

"难道我碰到喜欢的学生，就不能证明我不是靠胁迫赢得他的心吗？"
“难道我小心谨慎，一不留神碰到一个非要喜欢我的，我还洗不清楚了？”

很遗憾，是的。在强有力的监督下，禁止不平等权利下的恋爱关系，对于导师也是一种保护。首先，导师从职业道德出发，谨慎遵守各种规章制度，能够大大减少被“诬告”的几率。其次，如果真心相爱，师生之间完全可以等师生关系结束在开始恋爱关系，到那时就不存在“斜坡”的非议。最后，某些学生也会明白，如果跟导师发生超乎寻常的关系，不仅不会得到收益，反而会惹上一系列麻烦：这种情况也会减少某些有心计的学生的"计谋"。

需要注意的是，前文中所有的内容都有一个假设：存在第三方的、强有力的监督。当一个环境中不存在有效监督时，当一位导师犯了各种忌讳反而有人各种“灭火”时，当导师不在忌惮可能存在的严重后果时，权力就成了脱缰的野马。我们无法天真得期望狼不会吃羊，狼只会试探权力的边界，小心翼翼又肆无忌惮的捕食一个个猎物。如果权力没有监督，今天出现了陶同学，明天就回出现李同学，明年更会出现张同学，绵绵不绝。如何设置有效的监督，将学术圈中的权力锁到笼子里，现在看，笔者也没有答案。

The end. Thanks for reading. 